### ISSUE TITLE
About the installation of Deep Learning Framework

### ISSUE THREAD

**Issue by LongruiDong** [lsc19940810/SATNet#2]
Hi,
Thank you for sharing this excellent project,cause I am quite new to Pytorch，now I can only install pytorch 0.4.0,and I can not find this specific version from [pytorch.org](pytorch.org),
could you give more detail about installation of  **PyTorch 0.4.0a0+408c84d** ？

**Comment by ShiceLiu** [comment]
I installed this PyTorch version by the source code in the GitHub and I don't know whether you can get the exact version now. I am also sorry for the update of PyTorch because lots of functions and interfaces have been changes.
Thus, I suggest that you could install PyTorch 0.3.0 and change a few functions, such as 'torch.no_grad' to 'requires_grad'.
You could also install PyTorch 0.4.0 or latest version. But there might be more functions to rewrite. Because there seems to be no 'FloatTensor' class in the latest version.
I am afraid that you have to correct the code by yourself. However, in other versions, except the grammer error, there should be no logical error.

**Comment by ShiceLiu** [comment]
> Hi,
> Thank you for sharing this excellent project,cause I am quite new to Pytorch，now I can only install pytorch 0.4.0,and I can not find this specific version from [pytorch.org](pytorch.org),
> could you give more detail about installation of **PyTorch 0.4.0a0+408c84d** ？

I installed this PyTorch version by the source code in the GitHub and I don't know whether you can get the exact version now. I am also sorry for the update of PyTorch because lots of functions and interfaces have been changes.
Thus, I suggest that you could install PyTorch 0.3.0 and change a few functions, such as 'torch.no_grad' to 'requires_grad'.
You could also install PyTorch 0.4.0 or latest version. But there might be more functions to rewrite. Because there seems to be no 'FloatTensor' class in the latest version.
I am afraid that you have to correct the code by yourself. However, in other versions, except the grammer error, there should be no logical error.

**Comment by ShiceLiu** [comment]
@LongruiDong 

It is my pleasure that you are interested in this project.
I installed this PyTorch version by the source code in the GitHub and I don't know whether you can get the exact version now. I am also sorry for the update of PyTorch because lots of functions and interfaces have been changes.
Thus, I suggest that you could install PyTorch 0.3.0 and change a few functions, such as 'torch.no_grad' to 'requires_grad'.
You could also install PyTorch 0.4.0 or latest version. But there might be more functions to rewrite. Because there seems to be no 'FloatTensor' class in the latest version.
I am afraid that you have to correct the code by yourself. However, in other versions, except the grammer error, there should be no logical error.

**Comment by LongruiDong** [comment]
> @LongruiDong
> 
> It is my pleasure that you are interested in this project.
> I installed this PyTorch version by the source code in the GitHub and I don't know whether you can get the exact version now. I am also sorry for the update of PyTorch because lots of functions and interfaces have been changes.
> Thus, I suggest that you could install PyTorch 0.3.0 and change a few functions, such as 'torch.no_grad' to 'requires_grad'.
> You could also install PyTorch 0.4.0 or latest version. But there might be more functions to rewrite. Because there seems to be no 'FloatTensor' class in the latest version.
> I am afraid that you have to correct the code by yourself. However, in other versions, except the grammer error, there should be no logical error.

Thanks for reply!
I have figured out how to install **PyTorch 0.4.0a0+408c84d** from source, I write a simple script to get the history of  **commits**
in the directory of **pytorch**,run : 
```
import os
import sys

os.system("git log >> commit_log.txt")
```
Then search "408c84d" in commit_log.txt，I got the complete commit information:

```
commit 408c84de7c4d852beffb9c64e2351b16cfff8a1f
Author: Neeraj Pradhan <prad.neeraj@gmail.com>
Date:   Fri Jan 5 00:45:05 2018 -0800

    Supporting logits as parameters in Bernoulli and Categorical (#4448)

    * Supporting logits as parameters in Bernoulli and Categorical

    * address comments

    * fix lint

    * modify binary_cross_entropy_with_logits

    * address comments

    * add descriptor for lazy attributes

    * address comments
```
then check out this commit,
```
git checkout 408c84de7c4d852beffb9c64e2351b16cfff8a1f
```
after installation,I get the pytorch version
```
>>> torch.__version__
'0.4.0a0+408c84d'
```

**Comment by jiunyen-ching** [comment]
hi @LongruiDong, I am also trying to install pytorch using your method but the commit ID is not found in the logs. 

Comparing the same dates, here is what I found
```
commit 21d48be2dcab9ffcb51beef18d63d1d427f10612
Author: Edward Z. Yang <ezyang@fb.com>
Date:   Fri Jan 5 13:57:53 2018 -0800

    Delete redundant isContiguous check from THCUNN SpatialDilatedConvolution
    
    Signed-off-by: Edward Z. Yang <ezyang@fb.com>
```
I cloned pytorch from github before using ```os.system("git log >> commit_log.txt")```.

Can you advise me if we are doing it differently?

Update: searching for the commit ID in google colab is a big mistake. I downloaded the text file and found the commit ID.

**Comment by jiunyen-ching** [comment]
@LongruiDong may I ask what are your environment settings?

**Comment by jiunyen-ching** [comment]
Update: Able to recreate environment. Training - not tested, evaluation - tested working.

Environment settings:
- Ubuntu 16.04
- Python 2.7 (Anaconda)
- CUDA 9.0
- cuDNN 7

Steps:
1. Install requirements as per listed in pytorch's github page i.e. `conda install numpy ninja ... six requests`. 
2. Install dataclasses by `pip install dataclasses==0.6` because `conda install dataclasses` will have version clash.
3. `git clone --recursive https://github.com/pytorch/pytorch`
4. `cd pytorch`
5. Open terminal and type `git checkout 408c84de7c4d852beffb9c64e2351b16cfff8a1f`
6. `git submodule sync`
7. `git submodule update --init --recursive`
8. `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
9. `python setup.py install`
10. `pip install torchvision==0.2.0 --no-deps` (to avoid installing latest version of torch)
11. Install other dependencies as required by SATNet i.e. opencv, visdom

To verify pytorch installation:
1. `cd ..` (move one level out of pytorch folder)
2. `python`
3. `import torch`
4. `torch.__version__`
